name: CI/CD for Java Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Build and package with Maven
      run: mvn clean package

    - name: Debug Vercel Token
      run: |
        echo "Token length: ${#VERCEL_TOKEN}"
      shell: bash
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}